#!/bin/bash
set -Eeu -o pipefail

if [[ -t 0 && -t 1 ]]; then
  TTY_OPTION='-t'
else
  TTY_OPTION=''
fi
readonly TTY_OPTION
if command -v docker &>/dev/null; then
  # shellcheck disable=SC2086
  docker container run \
    --name "cmark-gfm_$(uuidgen | head -c8)" \
    --rm \
    -i \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work:ro \
    $TTY_OPTION \
    ghcr.io/shakiyam/cmark-gfm "$@"
else
  # shellcheck disable=SC2086
  podman container run \
    --name "cmark-gfm_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -i \
    -v "$PWD":/work:ro \
    $TTY_OPTION \
    ghcr.io/shakiyam/cmark-gfm "$@"
fi
