name: Check for updates
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check_for_image_updates:
    name: Check for image updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check_for_image_updates.sh
        run: ./tools/check_for_image_updates.sh "$(awk -e '/FROM/{print $2}' Dockerfile)" public.ecr.aws/docker/library/alpine:latest
  check_for_new_release:
    name: Check for new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check_for_new_release.sh
        run: ./tools/check_for_new_release.sh cmark-gfm github/cmark-gfm "$(awk -F= -e '/ENV CMARK_VERSION/{print $2}' Dockerfile)"
